# Generated by Django 5.1.6 on 2025-03-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
